### PR TITLE
add the pages links for the checkout process and the steps for the no…

### PR DESCRIPTION
**Pull request by jonathan-whitmire**
…tification feature

### CODE REVIEW

**Review by cmiller241 — DISMISSED** [review]
I couldn't get the radio buttons for the payment page to work.

**Comment by david420Revature** [comment]
please break the field inputs into their own when steps

**Comment by david420Revature** [comment]
there should probably be an extra given at the start to log the user in

**Review by david420Revature — APPROVED** [review]
thank you for breaking down the steps, everything seems to be functioning well

**Pull request merged**
