### PR TITLE
Corey features

### PR DESCRIPTION
**Pull request by cmiller241**
Included login, register, orders, and carts feature files.

### CODE REVIEW

**Comment by david420Revature** [comment]
I think login negative could use some more scenarios, or a scenario outline, for bad credentials (both fields invalid), bad username, bad password, and trying to login to an inactive account test

**Comment by david420Revature** [comment]
when using the scenario outlines, I think the accounts should be more generic and self descriptive (i.e. admin@example.com is site admin, test@example.com could be a non-admin account, and cart-tester@example.com make be an account with some items already in the cart). When we preload the h2 database with sql data, it'll be faster and easier if multiple tests can rely on the same data being loaded and unloaded before each test

**Comment by david420Revature** [comment]
#3 also contains a cart feature file

**Comment by cmiller241** [comment]
> I think login negative could use some more scenarios, or a scenario outline, for bad credentials (both fields invalid), bad username, bad password, and trying to login to an inactive account test

Thank you. Added.

**Comment by cmiller241** [comment]
> when using the scenario outlines, I think the accounts should be more generic and self descriptive (i.e. [admin@example.com](mailto:admin@example.com) is site admin, [test@example.com](mailto:test@example.com) could be a non-admin account, and [cart-tester@example.com](mailto:cart-tester@example.com) make be an account with some items already in the cart). When we preload the h2 database with sql data, it'll be faster and easier if multiple tests can rely on the same data being loaded and unloaded before each test

Thank you. Added.

**Comment by cmiller241** [comment]
I removed the cart folder to review duplication for later.

**Pull request merged**
