### PR TITLE
review, search features

### PR DESCRIPTION
**Pull request by mattjio**
added reviews and search feature files

### CODE REVIEW

**Comment by david420Revature** [comment]
line 9 in src/test/resources/features/search/search.feature is tabbed to far

**Comment by david420Revature** [comment]
Search for an item should probably be a scenario outline. Assuming the database is prefilled with multiple headphones, shirts, and bags; each category could be a tag to validate

**Comment by david420Revature** [comment]
negative review tests like: what happens if a review is too long, what happens when a malicious user puts in a <script>console.log("xss")</script> [is a malicious script tag created or will it be displayed as test?]

**Review by cmiller241 — APPROVED** [review]
Looks good Matthew. Please merge.

**Pull request merged**
